name: '@latest'

on:
  workflow_run:
    workflows:
      - main
    types:
      - completed

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Get latest published version
        id: get-version
        run: |
          PACKAGE_NAME="$(jq -r .name package.json)"
          echo "version=v$(npm show ${PACKAGE_NAME}@latest version || echo '0.0.0')" >> $GITHUB_OUTPUT

      - name: Checking out tag ${{ steps.get-version.outputs.version }}
        if: steps.get-version.outputs.version != 'v0.0.0'
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-version.outputs.version }}

      - name: Use Node LTS
        if: steps.get-version.outputs.version != 'v0.0.0'
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        if: steps.get-version.outputs.version != 'v0.0.0'
        run: corepack enable && pnpm install --frozen-lockfile

      - name: Run test suite
        if: steps.get-version.outputs.version != 'v0.0.0'
        run: pnpm run test
